asv-soft/asv-mavlink

.github/workflows/nuget_windows.yml

---
- https://app.asana.com/0/0/1204406391863511

Updated yml

---

.github/workflows/nuget_windows.yml

---
- https://app.asana.com/0/0/1204415559287341

Changed packages output path to projects path

---

.github/workflows/nuget_windows.yml

---
- https://app.asana.com/0/0/1204455172503816

Added test running step

---

README.md

---
- https://app.asana.com/0/0/1204598892957211

Added status badge for CI

---

src/Asv.Mavlink.Test/Microservices/AsvSdr/AsvSdrExTests.cs

---
- https://app.asana.com/0/0/1204455172503826

Implemented tests for AsvSdr extended client and server

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroserviceTest.cs
src/Asv.Mavlink/Microservices/Ftp/Client/Ex/FtpClientEx.cs
src/Asv.Mavlink/Microservices/Ftp/Payloads/FtpMessagePayload.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/FtpServerEx.cs

Change while true from both ftp ex to more controllable conditions
Asana: https://app.asana.com/0/1203851531040615/1204879661097384/f

fix: change while true from both ftp ex

---

src/Asv.Mavlink/Microservices/Commands/Client/CommandClientHelper.cs
src/Asv.Mavlink/RS.Designer.cs
src/Asv.Mavlink/RS.resx
src/Asv.Mavlink/RS.ru.resx

Asana: https://app.asana.com/0/1203851531040615/1204903646366551/f

feat: add localization to reboot and shutdown commands

---

src/Asv.Mavlink.Test/Tools/ListDataFileTest.cs

This commit includes additional unit tests for the ListDataFile class in order to increase code coverage. Tests were also added to verify the handling of null and incorrect arguments. A test was added to verify correct behavior when trying to read a file with different headers, and when providing incorrect version header or max size header. The cases where provided version or type fields are null, or empty type field, in ListDataFileFormat are tested as well. These added tests will help to catch potential bugs and erroneous behavior.
Asana: https://app.asana.com/0/1203851531040615/1205204009185597/f

feat(test): add additional test coverage for ListDataFile

---

src/Asv.Mavlink.Test/Microservices/Missions/MissionMicroserviceTest.cs

In this commit, multiple Unit Tests were added to the MissionMicroserviceTest.cs class. The added tests check the functionality of mission-related features such as setting the current mission, checking if a mission is reached, requesting the mission count, requesting specific mission items, and uploading missions. These tests are crucial to ensuring that the mission microservice functionality is working as expected.
Asana: https://app.asana.com/0/1203851531040615/1205600785681216/f

feat (tests): add tests for MissionMicroservice functionalities

---

src/Asv.Mavlink.Shell/Resources/csharp.tpl
src/Asv.Mavlink.Test/Microservices/AsvSdr/AsvSdrExTests.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/AsvSdrHelperTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/AsvSdrTest.cs
src/Asv.Mavlink/Devices/Sdr/Server/SdrServerDevice.cs
src/Asv.Mavlink/Microservices/AsvSdr/AsvSdrException.cs
src/Asv.Mavlink/Microservices/AsvSdr/AsvSdrHelper.cs
src/Asv.Mavlink/Microservices/AsvSdr/CalibrationTableRow.cs
src/Asv.Mavlink/Microservices/AsvSdr/Client/AsvSdrClient.cs
src/Asv.Mavlink/Microservices/AsvSdr/Client/Ex/AsvSdrClientCalibrationTable.cs
src/Asv.Mavlink/Microservices/AsvSdr/Client/Ex/AsvSdrClientEx.cs
src/Asv.Mavlink/Microservices/AsvSdr/Client/Ex/IAsvSdrClientEx.cs
src/Asv.Mavlink/Microservices/AsvSdr/Client/IAsvSdrClient.cs
src/Asv.Mavlink/Microservices/AsvSdr/Server/AsvSdrServer.cs
src/Asv.Mavlink/Microservices/AsvSdr/Server/Ex/AsvSdrServerEx.cs
src/Asv.Mavlink/Microservices/AsvSdr/Server/Ex/IAsvSdrServerEx.cs
src/Asv.Mavlink/Microservices/AsvSdr/Server/IAsvSdrServer.cs
src/Asv.Mavlink/Microservices/MavlinkMicroserviceClient.cs
src/Asv.Mavlink/Microservices/Missions/Client/Ex/MissionClientEx.cs
src/Asv.Mavlink/Protocol/Dialects/asv_sdr.xml
src/Asv.Mavlink/Protocol/Messages/asv_gbs.cs
src/Asv.Mavlink/Protocol/Messages/asv_sdr.cs
src/Asv.Mavlink/Protocol/Messages/common.cs

Added new mavlink messages to asv_sdr.xml:
+ ASV_SDR_OUT_STATUS.calib_state
+ ASV_SDR_OUT_STATUS.calib_table_count
+ASV_SDR_CALIB_ACC
+ASV_SDR_CALIB_TABLE_READ
+ASV_SDR_CALIB_TABLE
+ASV_SDR_CALIB_TABLE_ROW_READ
+ASV_SDR_CALIB_TABLE_ROW
+ASV_SDR_CALIB_TABLE_UPLOAD_START
+ASV_SDR_CALIB_TABLE_UPLOAD_READ_CALLBACK
Client\Server microservices implemented and tested
Asana: https://app.asana.com/0/1203851531040615/1205858132447991/f

Add calibration methods for SDR payload

---

src/Asv.Mavlink.Test/Microservices/TraceStream/TraceStreamMicroserviceTests.cs

add tests for bad values, overflow exception and add message of different types
asana: https://app.asana.com/0/1203851531040615/1206711763866034/f

test(trace-stream): add tests for bad values, overflow and add message of different types

---

src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtEncodingTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtMicroserviceTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtValueTest.cs
src/Asv.Mavlink/Microservices/ParamsExt/Tools/MavParamExtHelper.cs

Asana: https://app.asana.com/0/1203851531040615/1206968709037752/f

test(params-ext): add tests for constructors and encoding types

---

src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtEncodingTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtValueTest.cs
src/Asv.Mavlink/Microservices/ParamsExt/Tools/MavParamExtValue.cs

Asana:https://app.asana.com/0/1203851531040615/1207019921754312/f
---
- https://app.asana.com/0/0/1207019921754304

fix(params-extended): fix ambiguous call exception at MavParamExtValue constructor for each value type

---

src/Asv.Mavlink.Test/Asv.Mavlink.Test.csproj.DotSettings
src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtMicroserviceTest.cs

Asana: https://app.asana.com/0/1203851531040615/1206968709037752/f

test(params-ext): add read and write operations test

---

src/Asv.Mavlink/Tools/Router/IMavlinkRouter.cs
src/Asv.Mavlink/Tools/Router/MavlinkRouter.cs

https://app.asana.com/0/0/1207187765046405/f
---
- https://app.asana.com/0/0/1205820505097222

feat(mavlink): add packet loss simulation logic in MavlinkRouter

---

src/Asv.Mavlink.Test/Asv.Mavlink.Test.csproj
src/Asv.Mavlink.Test/Tools/Router/MavlinkRouterTest.cs
src/Asv.Mavlink/Tools/Router/IMavlinkRouter.cs
src/Asv.Mavlink/Tools/Router/MavlinkRouter.cs

Asana: https://app.asana.com/0/1203851531040615/1207219394377683/f

test (asv-mavlink) add simple tests to mavlink router to test packet loss

---

.github/workflows/release_nuget_github.yml

Asana: https://app.asana.com/0/1203851531040615/1207381092055967/f

feat (asv-mavlink): add workflow for nuget release on GitHub

---

src/Asv.Mavlink/Microservices/Missions/Client/Ex/IMissionClientEx.cs

feat(mission): add a new method DoChangeAltitude to IMissionClientEx and MissionClientExHelper to support altitude change mission items.
asana: https://app.asana.com/0/1203851531040615/1207379613116824/f

feat(mission): add new MissionItem DoChangeAltitude in IMissionClientEx

---

src/Asv.Mavlink/Microservices/Missions/Client/Ex/IMissionClientEx.cs

feat(mission): remove helper method for mission items DoChangeAltitude to IMissionClientEx
asana: https://app.asana.com/0/1203851531040615/1207454604949553/f

feat(mission): remove helper method for mission items DoChangeAltitude to IMissionClientEx

---

src/Asv.Mavlink/Tools/Router/MavlinkRouter.cs
src/Directory.Build.props

Asana: https://app.asana.com/0/1206009821057985/1207986882522777/f

fix(mavlink-router): right object dispose order, define actual project version in build properties

---

src/Asv.Mavlink/Tools/Router/MavlinkRouter.cs

Asana: https://app.asana.com/0/1203851531040615/1208210019969310/f

fix: use thread save Random.Shared and optimise packet loss

---

src/Asv.Mavlink.Test/Microservices/AsvRsga/AsvRsgaExTest.cs
src/Asv.Mavlink/Devices/Radio/Client/RadioClientDevice.cs
src/Asv.Mavlink/Devices/Vehicles/Client/Ardupilot/Plane/ArduPlaneClient.cs
src/Asv.Mavlink/Tools/HierarchicalStore/Impl/FileSystemHierarchicalStore.cs

Asana: https://app.asana.com/0/1203851531040615/1208349470710486/f

fix(mavlink): add logger initialization where it's missing

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroservice.Test.cs
src/Asv.Mavlink/Microservices/Ftp/Client/FtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/Client/IFtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/MavlinkFtpHelper.cs
src/Asv.Mavlink/Microservices/Ftp/Server/FtpServer.cs
src/Asv.Mavlink/Microservices/Ftp/Server/IFtpServer.cs

In this PR:
add Rename,RemoveDirectory,CalcFileCRC32,ResetSession,CreateDirectory,RemoveFile actions. Add server support, for these actions and unit tests
Asana:
https://app.asana.com/0/1203851531040615/1208388559101537/f
https://app.asana.com/0/1203851531040615/1208388559101541/f
https://app.asana.com/0/1203851531040615/1208388559101545/f
https://app.asana.com/0/1203851531040615/1208388559101549/f
https://app.asana.com/0/1203851531040615/1208388559101551/f
---
- https://app.asana.com/0/0/1208388559101543

feat(asv-mavlink-ftp): add client actions

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroservice.Test.cs
src/Asv.Mavlink/Microservices/Ftp/Client/FtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/Client/IFtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/Server/FtpServer.cs
src/Asv.Mavlink/Microservices/Ftp/Server/IFtpServer.cs

Asana: https://app.asana.com/0/1203851531040615/1208388559101547/f

feat: add rename command to IFtpClient

---

README.md
src/Asv.Mavlink.Shell/Asv.Mavlink.Shell.csproj
src/Asv.Mavlink.Shell/Commands/DevicesInfoCommand.cs
src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.Shell/Properties/launchSettings.json

Asana: https://app.asana.com/0/1203851531040615/1208405394310876/f

feat(shell): add devices info command

---

src/Asv.Mavlink.Shell/Commands/FtpBrowserDirectory.cs
src/Asv.Mavlink.Shell/Commands/FtpCommand.cs
src/Asv.Mavlink.Shell/Commands/FtpEntry.cs
src/Asv.Mavlink.Shell/Commands/FtpTreeDirectory.cs
src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroservice.Test.cs
src/Asv.Mavlink/Microservices/Ftp/Client/FtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/Client/IFtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/MavlinkFtpHelper.cs

add ftp commands ftp-browser and ftp-tree
asana: https://app.asana.com/0/1203851531040615/1208388559101531/f

feat(ftp): add ftpBrowser and ftpTree commands

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroservice.Test.cs
src/Asv.Mavlink/Microservices/Ftp/Client/IFtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/Server/FtpServer.cs
src/Asv.Mavlink/Microservices/Ftp/Server/IFtpServer.cs

Asana: https://app.asana.com/0/0/1208434201782092/f

feat: add burst read file to ftp server

---

src/Asv.Mavlink.Test/Asv.Mavlink.Test.csproj.DotSettings
src/Asv.Mavlink.Test/Microservices/PacketPrinter/PacketPrinter.Test.cs
src/Asv.Mavlink/Asv.Mavlink.csproj.DotSettings
src/Asv.Mavlink/PacketPrinter/DefaultPacketHandler.cs
src/Asv.Mavlink/PacketPrinter/FtpPacketHandler.cs
src/Asv.Mavlink/PacketPrinter/PacketPrinter.cs
src/Asv.Mavlink/PacketPrinter/ParamSetPacketHandler.cs
src/Asv.Mavlink/PacketPrinter/ParamValuePacketHandler.cs
src/Asv.Mavlink/PacketPrinter/StatusTextHandler.cs

Asana: https://app.asana.com/0/1203851531040615/1208426174517736/f

feat(mavlink): add PacketPrinter with handlers and converters to make strings from packets

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroservice.Test.cs
src/Asv.Mavlink/Microservices/Ftp/Client/FtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/Client/IFtpClient.cs
src/Asv.Mavlink/Microservices/Ftp/Server/FtpServer.cs
src/Asv.Mavlink/Microservices/Ftp/Server/IFtpServer.cs

fix(ftp): make ClcFileCrc32 return uint instead of int
feat(ftp-client): add WriteFile implementation
feat(ftp-server): add WriteFile implementation
feat(ftp-server): add CreateFile implementation
feat(ftp-client): add CreateFile implementation
feat(ftp-server): add OpenFileWrite implementation
feat(ftp-client): add OpenFileWrite implementation
fix(ftp-client): add ConfigureAwait(false) to CreateDirectory method
feat(ftp-server): add ListDirectory implementation
Asana: https://app.asana.com/0/1203851531040615/1208418977091204/f

feat(ftp): implement all missing methods

---

README.md
src/Asv.Mavlink.Shell/Adsb/VirtualAdsbCommand.cs
src/Asv.Mavlink.Shell/Benchmark/BenchmarkBinSerializationCommand.cs
src/Asv.Mavlink.Shell/Benchmark/BenchmarkSerializationPacket.cs
src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.Shell/Tests/ExportSdrData.cs
src/Asv.Mavlink.Shell/Tests/MavProxy.cs
src/Asv.Mavlink.Shell/Tests/MavlinkCommand.cs

asana: https://app.asana.com/0/1203851531040615/1208464714593592/f

feat(mavlink): rework the remaining commands to ConsoleAppFramework

---

src/Asv.Mavlink.Shell/Commands/FtpBrowserDirectory.cs
src/Asv.Mavlink.Shell/Commands/FtpTreeDirectory.cs

asana: https://app.asana.com/0/1203851531040615/1208451279092706/f

fix(ftp): add missing arguments to ftp commands browser and tree

---

src/Asv.Mavlink/Microservices/Ftp/Client/Ex/FtpClientEx.cs

Asana:
https://app.asana.com/0/1203851531040615/1208508427479271/f

FtpClientEx entries removing before adding

---

src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.Shell/Properties/launchSettings.json
src/Asv.Mavlink.Test/Asv.Mavlink.Test.csproj
src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroservice.Test.cs
src/Asv.Mavlink.Test/Microservices/Ftp/FtpServerEx.Tests.cs
src/Asv.Mavlink/Asv.Mavlink.csproj
src/Asv.Mavlink/Microservices/Ftp/Server/Crc32Mavlink.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/FtpServerEx.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/IFtpServerEx.cs
src/Asv.Mavlink/Microservices/Ftp/Server/FtpServer.cs

made FtpServer catch exceptions
Asana: https://app.asana.com/0/1203851531040615/1208465248348407/f

feat: add FtpServerEx and tests for it

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpServerEx.Tests.cs

Asana: https://app.asana.com/0/1203851531040615/1208539887289688/f

fix: change first part of root from D: to AppDomain.CurrentDomain.BaseDirectory

---

.github/workflows/release_pre_version.yml

Asana: https://app.asana.com/0/1203851531040615/1208544015473569/f

fix: remove --prerelease flags from release_pre_version.yml

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpMicroservice.Test.cs
src/Asv.Mavlink.Test/Microservices/Ftp/ServerUnitTests/FtpServerEx.Tests.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/FtpServerEx.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/IFtpServerEx.cs
src/Asv.Mavlink/Microservices/Ftp/Server/FtpServer.cs

add Ack response to InternalTerminateSession in ftp server, fix BurstReadFile test in FtpMicroservice.Test
Asana: https://app.asana.com/0/1203851531040615/1208533731626320/f

fix(ftp-server): make BurstReadFile read file to the end in bursts

---

.github/workflows/release-action.yml
.github/workflows/release_debug_version.yml
.github/workflows/release_pre_version.yml

Asana: https://app.asana.com/0/1203851531040615/1208587282391118/f

ci: update actions checkout and setup-dotnet to version 4

---

src/Asv.Mavlink.Test/Tools/FileSystemHierarchicalStoreTest.cs
src/Asv.Mavlink/Tools/HierarchicalStore/Impl/FileSystemHierarchicalStore.cs
src/Asv.Mavlink/Tools/HierarchicalStore/Impl/GuidHierarchicalStoreFormat.cs
src/Asv.Mavlink/Tools/ListDataFile/ListDataFile.cs

Asana: https://app.asana.com/0/1206009821057985/1208584551860957/f
---
- https://app.asana.com/0/0/1208584551860959

fix(list-data-file): change static File to IFileSystemInfo

---

README.md
src/Asv.Mavlink.Shell/Asv.Mavlink.Shell.csproj
src/Asv.Mavlink.Shell/Asv.Mavlink.Shell.csproj.DotSettings
src/Asv.Mavlink.Shell/Commands/GenerateDiagnostics/GenerateDiagnostics.cs
src/Asv.Mavlink.Shell/Commands/GenerateDiagnostics/GenerateDiagnosticsConfig.cs
src/Asv.Mavlink.Shell/Commands/VirtualFtpServer/CreateVirtualFtpServer.cs
src/Asv.Mavlink.Shell/Commands/VirtualFtpServer/VirtualFtpServerConfig.cs
src/Asv.Mavlink.Shell/Commands/VirtualFtpServer/VirtualFtpServerLogger.cs
src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.sln
src/Asv.Mavlink/Asv.Mavlink.csproj.DotSettings
src/Asv.Mavlink/Devices/Ftp/Server/FtpServerDevice.cs
src/Asv.Mavlink/Devices/Ftp/Server/IFtpServerDevice.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/FtpServerEx.cs

fix: block access to real file system root
Asana: https://app.asana.com/0/1203851531040615/1208598122348988/f

feat(shell): add command that creates virtual ftp server

---

src/Asv.Mavlink/Microservices/Ftp/Client/Ex/FtpClientEx.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/FtpServerEx.cs
src/Asv.Mavlink/Microservices/Ftp/Server/Ex/IFtpServerEx.cs

Asana:
https://app.asana.com/0/1203851531040615/1208617755314821/f

fix: Microsoft guide dispose methods 

---

src/Asv.Mavlink/Microservices/Ftp/Server/Ex/FtpServerEx.cs

Asana: https://app.asana.com/0/1206009821057985/1208575855373732/f

feat(ftp-server-ex): add log output

---

README.md

asana: https://app.asana.com/0/1203851531040615/1208636784407355/f

fix(readme): remove duplicate information in docs, fix pictures

---

src/Asv.Mavlink.Test/Tools/FileSystemHierarchicalStoreTest.cs
src/Asv.Mavlink.Test/Tools/ListDataFileTest.cs
src/Asv.Mavlink/Tools/HierarchicalStore/Impl/FileSystemHierarchicalStore.cs
src/Asv.Mavlink/Tools/HierarchicalStore/Impl/GuidHierarchicalStoreFormat.cs

Asana: https://app.asana.com/0/1206009821057985/1208584551860959/f
https://app.asana.com/0/1206009821057985/1208584551860957/f
---
- https://app.asana.com/0/0/1208605913889744
- https://app.asana.com/0/0/1208617772344056

Fix HierarchicalStore and ListDataFile tests with MockFileSystem abstraction

---

src/Asv.Mavlink.Shell/Adsb/VirtualAdsbCommand.cs
src/Asv.Mavlink.Test/Microservices/Adsb/AdsbVehicleComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Adsb/Client/AdsbVehicleClientTest.cs
src/Asv.Mavlink.Test/Microservices/Adsb/Client/AdsbVehicleTest.cs
src/Asv.Mavlink.Test/Microservices/Adsb/Server/AdsbVehicleServerTest.cs
src/Asv.Mavlink/Microservices/Adsb/Client/AdsbVehicleClient.cs
src/Asv.Mavlink/Microservices/Adsb/Server/AdsbVehicleServer.cs
src/Asv.Mavlink/Microservices/Adsb/Server/IAdsbVehicleServer.cs

asana: https://app.asana.com/0/1203851531040615/1208687174422745/f

test(adsb): add tests for server, client and complex test

---

src/Asv.Mavlink.Test/Microservices/StatusText/Client/StatusTextClientTest.cs
src/Asv.Mavlink.Test/Microservices/StatusText/Server/StatusTextServerTest.cs
src/Asv.Mavlink.Test/Microservices/StatusText/StatusTextComplexTest.cs
src/Asv.Mavlink/Microservices/StatusText/Client/StatusTextClient.cs
src/Asv.Mavlink/Microservices/StatusText/Server/StatusTextServer.cs

Asana: https://app.asana.com/0/1203851531040615/1208687175405358/f

add(status-text): unit tests for client server and both together

---

src/Asv.Mavlink.Test/Devices/Client/ClientDevice.Tests.cs
src/Asv.Mavlink.Test/Devices/ClientServerDevice.Tests.cs
src/Asv.Mavlink.Test/Devices/Server/ServerDevice.Tests.cs
src/Asv.Mavlink.Test/Microservices/AsvRadio/AsvRadioClientServerComplexTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRadio/Client/Ex/AsvRadioClientExTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRadio/Server/Ex/AsvRadioServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/FtpServerTest.cs
src/Asv.Mavlink/Microservices/AsvRadio/Client/Ex/AsvRadioClientEx.cs
src/Asv.Mavlink/Microservices/AsvRadio/Server/Ex/AsvRadioServerEx.cs

Asana: https://app.asana.com/0/1203851531040615/1208687174422742/f
---
- https://app.asana.com/0/0/1208687174422749

test(asv-radio): remove usings, code refactor, add unit and complex tests

---

src/Asv.Mavlink.Test/Tools/ListDataFile/ListDataFileTests.cs

Asana: https://app.asana.com/0/1203851531040615/1208687175405362/f

test(list-data-file): code and naming refactor

---

src/Asv.Mavlink.Test/Tools/HierarchicalStore/FileSystemHierarchicalStore.Tests.cs

Asana: https://app.asana.com/0/1206009821057985/1208687175405361/f

test(file-system-hierarchical-store): refactor tests according changes in test subject

---

src/Asv.Mavlink.Test/Asv.Mavlink.Test.csproj.DotSettings
src/Asv.Mavlink.Test/Microservices/ParamsExt/Client/Ex/ParamsExtClientExTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/Client/ParamsExtClientTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtComplexTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/Server/Ex/ParamsExtServerExTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/Server/ParamsExtServerTest.cs
src/Asv.Mavlink/Microservices/ParamsExt/Client/Ex/ParamsExtClientEx.cs
src/Asv.Mavlink/Microservices/ParamsExt/Client/ParamsExtClient.cs

asana: https://app.asana.com/0/1203851531040615/1208687175405357/f

test(ParamsExt): add server, client and complex tests

---

src/Asv.Mavlink.Test/Microservices/Missions/Client/Ex/MissionClientExTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/Client/MissionClientTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/Client/MissionItemTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/MissionComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/MissionExComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/Server/Ex/MissionServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/Server/MissionServerTest.cs
src/Asv.Mavlink/Microservices/Commands/Server/Ex/CommandServerEx.cs
src/Asv.Mavlink/Microservices/MavlinkMicroserviceClient.cs
src/Asv.Mavlink/Microservices/MavlinkMicroserviceServer.cs
src/Asv.Mavlink/Microservices/Missions/Client/Ex/MissionClientEx.cs
src/Asv.Mavlink/Microservices/Missions/Client/IMissionClient.cs
src/Asv.Mavlink/Microservices/Missions/Client/MissionClient.cs
src/Asv.Mavlink/Microservices/Missions/Client/MissionItem.cs
src/Asv.Mavlink/Microservices/Missions/Server/Ex/MissionServerEx.cs
src/Asv.Mavlink/Microservices/Missions/Server/IMIssionServer.cs
src/Asv.Mavlink/Microservices/Missions/Server/MissionServer.cs
src/Asv.Mavlink/Protocol/Messages/common.cs

feat: add ack packet handling on server side
feat: add ack send from client to server
fix: add set check for negative values in MissionClientConfig
Asana: https://app.asana.com/0/1203851531040615/1208687175405354/f

test: add tests for Mission microservice

---

src/Asv.Mavlink.Test/Microservices/AsvChart/AsvChartComplexTest.cs
src/Asv.Mavlink.Test/Microservices/AsvChart/Client/AsvChartClientTest.cs
src/Asv.Mavlink/Microservices/AsvChart/AsvChartOptions.cs
src/Asv.Mavlink/Microservices/AsvChart/Client/AsvChartClient.cs
src/Asv.Mavlink/Microservices/AsvChart/Server/AsvChartServer.cs
src/Asv.Mavlink/Protocol/Messages/asv_chart.cs

asana: https://app.asana.com/0/1203851531040615/1208687174422747/f

test(asvChart): add more complex tests and refactor some methods

---

src/Asv.Mavlink.Test/Microservices/Params/Client/Ex/ParamsClientExTest.cs
src/Asv.Mavlink.Test/Microservices/Params/Server/Ex/ParamsServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Params/Server/ParamsServerTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/Client/Ex/ParamsExtClientExTest.cs
src/Asv.Mavlink/Microservices/Params/Client/Ex/ParamsClientEx.cs
src/Asv.Mavlink/Microservices/Params/Server/Ex/ParamsServerEx.cs
src/Asv.Mavlink/Microservices/ParamsExt/Client/Ex/ParamsExtClientEx.cs

also small refactor
asana: https://app.asana.com/0/1203851531040615/1208833075215554/f

test(param\paramExt): add more tests for client in param and param ext microservices

---

src/Asv.Mavlink.Test/Microservices/Dgps/Client/DgpsClientTest.cs

asana: https://app.asana.com/0/1203851531040615/1208753847291915/f

test(dgps): add tests for client

---

src/Asv.Mavlink.Test/Microservices/AsvRsga/AsvRsgaComplexTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Client/AsvRsgaClientTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Client/Ex/AsvRsgaClientExTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Server/AsvRsgaServerTest.cs
src/Asv.Mavlink/Microservices/AsvRsga/Client/Ex/AsvRsgaClientEx.cs

asana: https://app.asana.com/0/1203851531040615/1208687175405346/f

test(rsga): add tests for client and server. Add complex tests

---

src/Asv.Mavlink.Shell/Asv.Mavlink.Shell.csproj
src/Asv.Mavlink.Shell/Commands/FtpBrowserDirectory.cs
src/Asv.Mavlink.Shell/Commands/FtpTreeDirectory.cs
src/Asv.Mavlink.Shell/Commands/Utils/FtpEntry.cs
src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.Shell/Properties/launchSettings.json

Asana: https://app.asana.com/0/1203851531040615/1208786090878772/f

fix(shell): ftp-tree & ftp-browser commands

---

src/Asv.Mavlink.Test/Microservices/AsvRsga/Client/AsvRsgaClientTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Client/Ex/AsvRsgaClientExTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Server/AsvRsgaServerTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/MissionComplexTest.cs

asana: https://app.asana.com/0/1203851531040615/1208901875152198/f

fix(tests): small refactor after merge

---

src/Asv.Mavlink.Test/Microservices/AsvSdr/Server/AsvSdrServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/Server/Ex/AsvSdrServerExTest.cs

asana: https://app.asana.com/0/1203851531040615/1208910326574021/f

test(sdr): add server tests

---

src/Asv.Mavlink.Test/Microservices/Adsb/Server/AdsbVehicleServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvGbs/Server/AsvGbsServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Server/AsvRsgaServerTest.cs
src/Asv.Mavlink.Test/Microservices/Commands/Server/CommandServerTest.cs

refactor test with valid assert of throw exception type OperationCancelledException. add more tests with cancel
Asana: https://app.asana.com/0/1203851531040615/1208753847291917/f

fix(microservice-tests): fix tests

---

src/Asv.Mavlink.Test/Devices/ClientServerDevice.Tests.cs
src/Asv.Mavlink.Test/Microservices/AsvGbs/Server/AsvGbsServerTest.cs
src/Asv.Mavlink.Test/Microservices/Commands/CommandIntComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Commands/CommandLongComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Heartbeat/Client/HeartbeatClientTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/Client/Ex/MissionClientExTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/MissionExComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Params/Client/Ex/ParamsClientExTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/Client/Ex/ParamsExtClientExTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/ParamsExtComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Position/PositionExComplexTest.cs
src/Asv.Mavlink/Microservices/ParamsExt/Client/Ex/ParamsExtClientEx.cs
src/Asv.Mavlink/Microservices/ParamsExt/Tools/MavParamExtValue.cs

Asana: https://app.asana.com/0/1203851531040615/1208881132443172/f

test(mavlink-microservices): fix tests, skip not relevant or not stable tests for future refactoring

---

src/Asv.Mavlink.Test/Asv.Mavlink.Test.csproj.DotSettings
src/Asv.Mavlink.Test/Microservices/AsvSdr/Store/AsvSdrStoreTests.cs
src/Asv.Mavlink/Microservices/AsvSdr/Store/AsvSdrRecordFileHelper.cs

Asana: https://app.asana.com/0/1203851531040615/1208910326574022/f

test(sdr-store): add tests for helper, metadata,format

---

src/Asv.Mavlink.Test/Microservices/AsvSdr/AsvSdrHelperTest.cs
src/Asv.Mavlink/Microservices/AsvSdr/AsvSdrHelper.cs

Asana: https://app.asana.com/0/1203851531040615/1208918462616624/f

test: AsvSdrHelper

---

src/Asv.Mavlink.Test/Microservices/Adsb/Server/AdsbVehicleServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvGbs/Server/AsvGbsServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/Store/AsvSdrStoreTests.cs
src/Asv.Mavlink.Test/Microservices/Commands/Server/CommandServerTest.cs
src/Asv.Mavlink.Test/Microservices/Telemetry/Client/TelemetryClientTest.cs

Asana: https://app.asana.com/0/1203851531040615/1208983786941058/f

fix(mavlink-test): fix tests

---

src/Asv.Mavlink.Test/Microservices/Ftp/Client/FtpClientTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/FtpExComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/Ex/FtpServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/FtpServerTest.cs
src/Asv.Mavlink.Test/Microservices/StatusText/StatusTextComplexTest.cs

Asana: https://app.asana.com/0/1203851531040615/1208983786941058/f

test: cancellation tokens timeouts removed (u02) 

---

src/Asv.Mavlink.Test/Microservices/Ftp/Client/FtpClientTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/FtpExComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/Ex/FtpServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/FtpServerTest.cs

Asana: https://app.asana.com/0/1203851531040615/1208988484062979/f

test(ftp-server): remove cancellation token lifetime add tests

---

src/Asv.Mavlink.Test/Microservices/AsvSdr/Client/AsvSdrClientTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/Client/Ex/AsvSdrClientCalibrationTableTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/Client/Ex/AsvSdrClientExTest.cs

Asana: https://app.asana.com/0/1203851531040615/1208910326574020/f

test(client-test): add client and clientEx tests, calibration table tests

---

src/Asv.Mavlink.Test/Microservices/AsvSdr/AsvSdrComplexTests.cs

Asana: https://app.asana.com/0/1203851531040615/1208983786941058/f

test(sdr): add complex tests for extended sdr

---

src/Asv.Mavlink.Test/Devices/Server/ServerDeviceBuilderTests.cs
src/Asv.Mavlink.Test/Microservices/Mode/Client/ClientModeTest.cs
src/Asv.Mavlink/Microservices/Mode/Server/ModeServer.cs

Asana: https://app.asana.com/0/1203851531040615/1209033497705427/f

test(server-device-builder): add test? fix problems and errors

---

src/Asv.Mavlink.Test/Microservices/Mode/Client/ClientModeTest.cs
src/Asv.Mavlink.Test/Microservices/Mode/ModeClientComplexTest.cs
src/Asv.Mavlink/Microservices/Mode/Server/ModeServer.cs

Asana: https://app.asana.com/0/1203851531040615/1209013278910506/f

test(mode): add tests complex test, fix ModeServer.cs

---

src/Asv.Mavlink.Test/Devices/Server/ServerDevice.Tests.cs
src/Asv.Mavlink.Test/Devices/Server/ServerDeviceBuilderTests.cs
src/Asv.Mavlink.Test/Microservices/Adsb/Server/AdsbVehicleServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvChart/Server/AsvChartServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvGbs/Server/AsvGbsServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvGbs/Server/Ex/AsvGbsExServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRadio/Server/AsvRadioServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRadio/Server/Ex/AsvRadioServerExTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Server/AsvRsgaServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvRsga/Server/Ex/AsvRsgaServerExTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/Server/AsvSdrServerTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/Server/Ex/AsvSdrServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Commands/Server/CommandServerTest.cs
src/Asv.Mavlink.Test/Microservices/Diagnostic/Server/DiagnosticServerTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/Ex/FtpServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/FtpServerTest.cs
src/Asv.Mavlink.Test/Microservices/Heartbeat/Server/HeartbeatServerTest.cs
src/Asv.Mavlink.Test/Microservices/Logging/Server/LoggingServerTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/Server/Ex/MissionServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/Server/MissionServerTest.cs
src/Asv.Mavlink.Test/Microservices/Params/Server/Ex/ParamsServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Params/Server/ParamsServerTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/Server/Ex/ParamsExtServerExTest.cs
src/Asv.Mavlink.Test/Microservices/ParamsExt/Server/ParamsExtServerTest.cs
src/Asv.Mavlink.Test/Microservices/ServerTestBase.cs
src/Asv.Mavlink.Test/Microservices/StatusText/Server/StatusTextServerTest.cs
src/Asv.Mavlink.Test/Microservices/V2Extention/Server/V2ExtensionServerTest.cs

asana: https://app.asana.com/0/1203851531040615/1208705173494165/f

fix(tests): fix typo in server base class

---

src/Asv.Mavlink.Shell/Commands/PacketViewerCommand.cs
src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.Shell/Properties/launchSettings.json
src/Asv.Mavlink.Shell/Tests/ParamsCommand.cs
src/Asv.Mavlink.Shell/Tests/PrintVehicleState.cs
src/Asv.Mavlink.Shell/Tests/ShellCommandsHelper.cs
src/Asv.Mavlink/Devices/Client/Vehicles/VehicleClientDevice.cs
src/Directory.Build.props

-Spectre Console library to improve visual
-Add helper with router and device explorer creation methods
Asana: https://app.asana.com/0/1203851531040615/1208464714593592/f

Fix commands in Asv.Mavlink.Shell 

---

src/Asv.Mavlink.Shell/CodeGen/ExampleCommand.cs
src/Asv.Mavlink.Shell/Program.cs
src/Asv.Mavlink.Shell/Properties/launchSettings.json

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1209315664743519?focus=true

feat(shell): improve ExampleCommand

---

src/Asv.Mavlink.Shell/Asv.Mavlink.Shell.csproj
src/Asv.Mavlink.Shell/Commands/DevicesInfoCommand.cs
src/Asv.Mavlink.Test/Asv.Mavlink.Test.csproj
src/Asv.Mavlink.Test/Microservices/AsvRadio/AsvRadioClientServerComplexTest.cs
src/Asv.Mavlink.Test/Microservices/AsvSdr/Client/AsvSdrClientTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Client/FtpClientTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/FtpComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/FtpExComplexTest.cs
src/Asv.Mavlink.Test/Microservices/Ftp/Server/Ex/FtpServerExTest.cs
src/Asv.Mavlink.Test/Microservices/Missions/MissionComplexTest.cs
src/Asv.Mavlink/Asv.Mavlink.csproj
src/Asv.Mavlink/Microservices/Ftp/Client/Ex/FtpClientEx.cs
src/Asv.Mavlink/Microservices/Ftp/MavlinkFtpHelper.cs
src/Directory.Build.props

make ftp tests work for all unix file systems
make Client_DisableRadio_Success test case work properly
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210902613481121?focus=true

feat: update to net core 9

---

src/Asv.Mavlink.Test/Microservices/Ftp/FtpExComplexTest.cs
src/Asv.Mavlink/Microservices/Ftp/Client/Ex/FtpClientEx.cs
src/Asv.Mavlink/Microservices/Ftp/Client/Ex/IFtpClientEx.cs
src/Directory.Build.props

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210982999345191?focus=true

feat(ftp-client): implement RemoveDirectory method with recursive and non-recursive options

---

.github/workflows/release-action.yml
.github/workflows/release_debug_version.yml
src/Directory.Build.props

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1211182049038208?focus=true

feat: update to version 4.0.17

---

.github/workflows/release-action.yml
.github/workflows/release_debug_version.yml
src/Directory.Build.props

Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1211194034054324?focus=true

feat: remove net8.0
